-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 10:11:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema propex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema propex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `propex` DEFAULT CHARACTER SET utf8mb4 ;
USE `propex` ;

-- -----------------------------------------------------
-- Table `propex`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`projects` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `program` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `start_season` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `included_courses` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pcc_and_course_calendar` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `required_courses_credits` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `infrastructure` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `public_participation` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `accompaniment_and_evaluation` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`activities` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `external` TINYINT(1) NOT NULL DEFAULT 0,
  `number_of_members` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `period` INT(11) NOT NULL,
  `execution_weekday` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `execution_hour` TIME NOT NULL,
  `results` VARCHAR(180) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `projects_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_projects1_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_activities_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `propex`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`attachments` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('document', 'image', 'video', 'publication', 'event', 'assigns_list', 'other') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `original_file_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `original_file_size` DOUBLE(8,2) NOT NULL,
  `file_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `file_size` DOUBLE(8,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`activity_attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`activity_attachments` (
  `activity_id` BIGINT(20) UNSIGNED NOT NULL,
  `attachment_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`activity_id`, `attachment_id`),
  INDEX `activity_attachments_activity_id_foreign` (`activity_id` ASC) VISIBLE,
  INDEX `activity_attachments_attachment_id_foreign` (`attachment_id` ASC) VISIBLE,
  CONSTRAINT `activity_attachments_activity_id_foreign`
    FOREIGN KEY (`activity_id`)
    REFERENCES `propex`.`activities` (`id`),
  CONSTRAINT `activity_attachments_attachment_id_foreign`
    FOREIGN KEY (`attachment_id`)
    REFERENCES `propex`.`attachments` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`students` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `course` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `period` INT(11) NOT NULL,
  `scholarship` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  `students_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_users_email` (`email` ASC) VISIBLE,
  INDEX `idx_users_students_id` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_students`
    FOREIGN KEY (`students_id`)
    REFERENCES `propex`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`collaborators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`collaborators` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `academic_function` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `profissional_registry` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `link_format` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `collaborators_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `collaborators_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `propex`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`disclosure_medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`disclosure_medias` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `date` DATE NOT NULL,
  `link` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `disclosure_medias_project_id_foreign` (`project_id` ASC) VISIBLE,
  CONSTRAINT `disclosure_medias_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`event_presentations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`event_presentations` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `date` DATE NOT NULL,
  `modality` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `event_presentations_project_id_foreign` (`project_id` ASC) VISIBLE,
  CONSTRAINT `event_presentations_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`extension_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`extension_lines` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT(11) NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `operation` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`evaluation` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `finished_projects_project_id_foreign` (`project_id` ASC) VISIBLE,
  CONSTRAINT `finished_projects_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`future_development_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`future_development_plans` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `activities` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `expected_results` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `participants_number` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `future_development_plans_project_id_foreign` (`project_id` ASC) VISIBLE,
  CONSTRAINT `future_development_plans_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`human_resource_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`human_resource_types` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`partners` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `contact` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `involved_partners_project_id_foreign` (`project_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `involved_partners_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`knowledge_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`knowledge_areas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`demands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`demands` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `justification` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `new_demands_project_id_foreign` (`project_id` ASC) VISIBLE,
  CONSTRAINT `new_demands_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`publications` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `attachment_id` BIGINT(20) UNSIGNED NULL,
  `type` ENUM('artigo','capitulo','resumo') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `journal_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `link` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `performed_publications_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `performed_publications_attachment_id_foreign` (`attachment_id` ASC) VISIBLE,
  CONSTRAINT `performed_publications_attachment_id_foreign`
    FOREIGN KEY (`attachment_id`)
    REFERENCES `propex`.`attachments` (`id`),
  CONSTRAINT `performed_publications_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`permissions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `url` VARCHAR(180) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_attachments` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `attachment_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `attachment_id`),
  INDEX `project_attachments_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `project_attachments_attachment_id_foreign` (`attachment_id` ASC) VISIBLE,
  CONSTRAINT `project_attachments_attachment_id_foreign`
    FOREIGN KEY (`attachment_id`)
    REFERENCES `propex`.`attachments` (`id`),
  CONSTRAINT `project_attachments_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_extension_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_extension_lines` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `extension_line_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `extension_line_id`),
  INDEX `project_extension_lines_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `project_extension_lines_extension_line_id_foreign` (`extension_line_id` ASC) VISIBLE,
  CONSTRAINT `project_extension_lines_extension_line_id_foreign`
    FOREIGN KEY (`extension_line_id`)
    REFERENCES `propex`.`extension_lines` (`id`),
  CONSTRAINT `project_extension_lines_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_human_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_human_resources` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `human_resource_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `coordinate` TINYINT(1) NOT NULL DEFAULT 0,
  `exclusive` TINYINT(1) NOT NULL DEFAULT 0,
  `workload` INT(11) NOT NULL,
  `initiated_at` DATE NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `project_human_resources_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `project_human_resources_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `project_human_resources_human_resource_type_id_foreign` (`human_resource_type_id` ASC) VISIBLE,
  CONSTRAINT `project_human_resources_human_resource_type_id_foreign`
    FOREIGN KEY (`human_resource_type_id`)
    REFERENCES `propex`.`human_resource_types` (`id`),
  CONSTRAINT `project_human_resources_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`),
  CONSTRAINT `project_human_resources_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `propex`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_knowledge_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_knowledge_areas` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `knowledge_area_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `knowledge_area_id`),
  INDEX `project_knowledge_areas_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `project_knowledge_areas_knowledge_area_id_foreign` (`knowledge_area_id` ASC) VISIBLE,
  CONSTRAINT `project_knowledge_areas_knowledge_area_id_foreign`
    FOREIGN KEY (`knowledge_area_id`)
    REFERENCES `propex`.`knowledge_areas` (`id`),
  CONSTRAINT `project_knowledge_areas_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`publics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`publics` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cras` VARCHAR(180) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_publics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_publics` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `public_id` BIGINT(20) UNSIGNED NOT NULL,
  `directly` TINYINT(1) NOT NULL DEFAULT 0,
  `other_public_title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `other_public_cras` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`project_id`, `public_id`),
  INDEX `project_publics_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `project_publics_public_id_foreign` (`public_id` ASC) VISIBLE,
  CONSTRAINT `project_publics_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`),
  CONSTRAINT `project_publics_public_id_foreign`
    FOREIGN KEY (`public_id`)
    REFERENCES `propex`.`publics` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_targets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_targets` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `men_number` INT(11) NULL DEFAULT 0,
  `women_number` INT(11) NULL DEFAULT 0,
  `age_range` ENUM('Até 12 anos incompletos','Até 18 anos','De 19 a 25 anos','De 26 a 30 anos','De 31 a 50 anos','De 51 a 60 anos','De 61a 70 anos','Acima de 70 anos') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `project_targets_project_id_foreign` (`project_id` ASC) VISIBLE,
  CONSTRAINT `project_targets_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`theme_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`theme_areas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`project_theme_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`project_theme_areas` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL,
  `theme_area_id` BIGINT(20) UNSIGNED NOT NULL,
  `main` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CUREENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`project_id`, `theme_area_id`),
  INDEX `project_theme_areas_project_id_foreign` (`project_id` ASC) VISIBLE,
  INDEX `project_theme_areas_theme_area_id_foreign` (`theme_area_id` ASC) VISIBLE,
  CONSTRAINT `project_theme_areas_project_id_foreign`
    FOREIGN KEY (`project_id`)
    REFERENCES `propex`.`projects` (`id`),
  CONSTRAINT `project_theme_areas_theme_area_id_foreign`
    FOREIGN KEY (`theme_area_id`)
    REFERENCES `propex`.`theme_areas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `propex`.`user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propex`.`user_permissions` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `permission_id`),
  INDEX `user_permissions_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `user_permissions_permission_id_foreign` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `user_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `propex`.`permissions` (`id`),
  CONSTRAINT `user_permissions_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `propex`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
